### ISSUE TITLE
SMTP client not working

### ISSUE THREAD

**Issue by MasterKeyxda** [cdzombak/runner#9]
When I use the smtp strings to send email it does not work.

 runner -mailto 'def@gmail.com' -mail-from 'abc@gmail.com' -smtp-host 'smtp.gmail.com' -smtp-port 587 -smtp-user 'abc@gmail.com' -smtp-pass 'abd'  command

https://github.com/xhit/go-simple-mail/v2

In deliver.go you are importing:

	mail "github.com/xhit/go-simple-mail/v2"

The v2 branch link is dead.

Would replacing the line with:

     mail "github.com/xhit/go-simple-mail/tree/v2.16.0"

fix the problem?

**Comment by MasterKeyxda** [comment]
Any thoughts?

**Comment by cdzombak** [comment]
Thank you for the bug report. v2.11.0, which [CI is now working on releasing](https://github.com/cdzombak/runner/actions/runs/19015550370), should fix this for you. I've also filed #11 as a reminder for myself to make this more flexible moving forward.

**Comment by MasterKeyxda** [comment]
When will the apt repository be updated? I still can't upgrade with apt.

**Comment by cdzombak** [comment]
> When will the apt repository be updated? I still can't upgrade with apt.

CI ran into a Tailscale ACL issue, but it should be resolved and caches flushed now.

**Comment by MasterKeyxda** [comment]
Tested. Received the email. Closing this issue.
